[package]
name = "timada"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
tokio = { version = "1.45", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "any"] }
liteventd = { path = "./liteventd" }

[workspace]
members = [
  "liteventd",
  "macros"
]

[profile.release]
codegen-units = 1
panic = "abort"
lto = true
strip = true

