services:
  db:
    image: postgres:17.5-alpine
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: postgres
    networks:
      - intranet

  timada-migrate:
    image: timayz/timada
    command: migrate -c /home/timada/config.toml
    volumes:
      - timada:/var/lib/timada
      - timada.standalone.toml:/home/timada/config.toml
    restart: on-failure
    profiles:
      - standalone
    networks:
      - intranet
    depends_on:
      - db
      
  timada:
    image: timayz/timada
    command: serve -c /home/timada/config.toml
    volumes:
      - timada:/var/lib/timada
      - timada.standalone.toml:/home/timada/config.toml
    restart: on-failure
    profiles:
      - standalone
    networks:
      - intranet
    depends_on:
      - timada-migrate
      - db

volumes:
  timada:

networks:
  intranet:
    name: timada
