//! Write-side commands for [`Cart`](crate::aggregate::Cart).
//!
//! The cart id is chosen by the caller (it comes from the browser's cookie),
//! never generated by `evento::create()` — that is why the first add appends
//! at version 0 to an id that does not exist yet, and every later write goes
//! through [`ProjectionAggregate::write`], which carries the replayed version
//! into the optimistic-concurrency check.

use evento::ProjectionAggregate as _;
use timada_catalog::ProductView;
use timada_core::{Executor, Money};

use crate::aggregate::{CartCheckedOut, CartItemAdded, CartItemRemoved};
use crate::view::load_cart;

/// Why an "add to cart" was refused.
///
/// Split from the storage failures so the storefront can answer a bad request
/// with a 400 and a real reason, instead of a blanket 500.
#[derive(Debug, thiserror::Error)]
pub enum AddItemError {
    #[error("quantity must be at least 1")]
    InvalidQuantity,
    #[error("this product is not available for sale")]
    ProductUnavailable,
    #[error("cart already checked out")]
    CartCheckedOut,
    #[error(transparent)]
    Storage(#[from] anyhow::Error),
}

/// Put `quantity` units of `product` in the cart.
///
/// The product is passed in rather than looked up here so the caller owns the
/// "does this product exist" answer (a 404, not a 400) and so the cart never
/// depends on the catalog's eventually-consistent read models.
///
/// A checked-out cart is refused rather than silently reopened: the cookie is
/// stale, and the caller's job is to mint a fresh cart id and retry.
#[tracing::instrument(skip(executor, product), fields(product_id = %product.id))]
pub async fn add_item(
    executor: &Executor,
    cart_id: &str,
    product: &ProductView,
    quantity: u32,
) -> Result<(), AddItemError> {
    if quantity == 0 {
        return Err(AddItemError::InvalidQuantity);
    }
    if !product.published || product.archived {
        return Err(AddItemError::ProductUnavailable);
    }

    let added = CartItemAdded {
        product_id: product.id.clone(),
        title: product.title.clone(),
        unit_price: Money::new(product.price_cents, product.currency),
        supplier_id: product.supplier_id.clone(),
        supplier_product_ref: product.supplier_product_ref.clone(),
        quantity,
    };

    let mut write = match load_cart(executor, cart_id).await? {
        Some(cart) if cart.checked_out => return Err(AddItemError::CartCheckedOut),
        Some(cart) => cart.write()?,
        // First event of a cart the customer's cookie already names: append at
        // the builder's default `original_version` of 0, which is exactly the
        // expected version of an id with no events yet.
        None => evento::append(cart_id),
    };

    write
        .event(&added)
        .commit(executor)
        .await
        .map_err(anyhow::Error::from)?;

    tracing::info!(cart_id, quantity, "cart item added");
    Ok(())
}

/// Drop a product from the cart entirely, whatever its quantity.
///
/// Every failure mode here means the customer's intent is already satisfied —
/// the line is not in the cart — so all of them are logged and ignored rather
/// than raised: a double-clicked Remove button should not produce an error
/// page.
#[tracing::instrument(skip(executor))]
pub async fn remove_item(
    executor: &Executor,
    cart_id: &str,
    product_id: &str,
) -> anyhow::Result<()> {
    let Some(cart) = load_cart(executor, cart_id).await? else {
        tracing::warn!(cart_id, "cannot remove from an unknown cart");
        return Ok(());
    };

    if cart.checked_out {
        tracing::warn!(cart_id, "cannot remove from a checked-out cart");
        return Ok(());
    }

    if !cart.lines.iter().any(|line| line.product_id == product_id) {
        tracing::info!(cart_id, product_id, "cart line already absent");
        return Ok(());
    }

    cart.write()?
        .event(&CartItemRemoved {
            product_id: product_id.to_owned(),
        })
        .commit(executor)
        .await?;

    tracing::info!(cart_id, product_id, "cart item removed");
    Ok(())
}

/// Close the cart because it became an order.
///
/// Called by the checkout flow after the order is placed, as a separate commit
/// from the order's own — the two aggregates are eventually consistent, and an
/// order whose cart is briefly still open is harmless (the customer sees the
/// cart empty on the next add, which mints a fresh id).
#[tracing::instrument(skip(executor))]
pub async fn mark_checked_out(executor: &Executor, cart_id: &str) -> anyhow::Result<()> {
    let Some(cart) = load_cart(executor, cart_id).await? else {
        tracing::warn!(cart_id, "cannot check out an unknown cart");
        return Ok(());
    };

    if cart.checked_out {
        tracing::info!(cart_id, "cart already checked out");
        return Ok(());
    }

    cart.write()?
        .event(&CartCheckedOut)
        .commit(executor)
        .await?;

    tracing::info!(cart_id, "cart checked out");
    Ok(())
}
