global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  insecure: false
  dashboard: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    network: timada
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/timada.crt
        keyFile: /etc/traefik/certs/timada.key
