[package]
name = "timada-customer"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
timada-core.workspace = true
evento.workspace = true
bitcode.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
timada-core = { workspace = true, features = ["test-support"] }
tokio.workspace = true

[lints]
workspace = true
