- id: "ory:kratos:public"
  upstream:
    preserve_host: true
    url: "http://kratos:4433"
    strip_path: /oath/.ory/kratos/public
  match:
    url: "https://timada.localhost/oath/.ory/kratos/public/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop

- id: "timada:root"
  upstream:
    preserve_host: true
    url: "http://timada:3000"
  match:
    url: "https://timada.localhost/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: anonymous
    # - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
  errors:
    - handler: redirect
      config:
        to: https://timada.localhost/oath/login
# - id: "ory:kratos-selfservice-ui-node:anonymous"
#   upstream:
#     preserve_host: true
#     url: "http://kratos-selfservice-ui-node:4435"
#     strip_path: /oath
#   match:
#     url: "https://timada.localhost/oath/<{welcome,registration,login,verification,error,recovery,verify,auth/*,**.css,**.js,**.png}{/,}>"
#     methods:
#       - GET
#   authenticators:
#     - handler: anonymous
#   authorizer:
#     handler: allow
#   mutators:
#     - handler: noop
#
# - id: "ory:kratos-selfservice-ui-node:protected"
#   upstream:
#     preserve_host: true
#     url: "http://kratos-selfservice-ui-node:4435"
#     strip_path: /oath
#   match:
#     url: "https://timada.localhost/oath/<{,debug,dashboard,settings}>"
#     methods:
#       - GET
#   authenticators:
#     - handler: cookie_session
#   authorizer:
#     handler: allow
#   mutators:
#     - handler: id_token
#   errors:
#     - handler: redirect
#       config:
#         to: https://timada.localhost/oath/login

